import {
  ProcurementCentre,
  FarmerProfile,
  Booking,
  ProcurementRecord,
  PaymentRecord,
  AppNotification,
  AdminAlert,
  DynamicSlot
} from '../types';

export const mockFarmerProfile: FarmerProfile = {
  id: 'farmer-101',
  name: 'Ramesh Patel',
  phone: '+91 98451 23890',
  aadhaarMasked: 'XXXX-XXXX-4819',
  farmerId: 'KA-MND-2024-8841',
  village: 'Keregodu',
  taluk: 'Mandya Taluk',
  district: 'Mandya',
  state: 'Karnataka',
  landSizeAcres: 4.5,
  primaryCrop: 'Paddy (Grade A)',
  bankAccountMasked: 'XXXX-XXXX-9142',
  bankName: 'State Bank of India (Mandya Main)',
  ifscCode: 'SBIN0001234',
};

export const initialCentres: ProcurementCentre[] = [
  {
    id: 'centre-a',
    name: 'Mandya Central APMC Yard',
    code: 'MND-APMC-01',
    district: 'Mandya',
    address: 'APMC Market Yard, Sugar Town, Mandya - 571401',
    latitude: 12.5244,
    longitude: 76.8958,
    distanceKm: 8.2,
    capacityQuintalsPerDay: 5000,
    currentCapacityUsedQuintals: 4600,
    capacityUtilizationPercent: 92,
    activeWeighingStations: 4,
    totalWeighingStations: 4,
    queueSize: 87,
    averageWaitMinutes: 240, // 4 hours
    processingRatePerHour: 18,
    status: 'CONGESTED',
    delayMinutes: 0,
    isRecommended: false,
    contactPhone: '+91 8232-224501',
    operatingHours: '08:00 AM - 06:00 PM',
  },
  {
    id: 'centre-b',
    name: 'Gejjalagere Farmers Sub-Centre',
    code: 'MND-SUB-04',
    district: 'Mandya',
    address: 'Mysuru-Bengaluru Highway, Gejjalagere - 571428',
    latitude: 12.5651,
    longitude: 76.9532,
    distanceKm: 11.4,
    capacityQuintalsPerDay: 3500,
    currentCapacityUsedQuintals: 2135,
    capacityUtilizationPercent: 61,
    activeWeighingStations: 3,
    totalWeighingStations: 3,
    queueSize: 31,
    averageWaitMinutes: 100, // 1h 40m
    processingRatePerHour: 14,
    status: 'OPTIMAL',
    delayMinutes: 0,
    isRecommended: true,
    recommendationReasons: [
      'Lowest expected waiting time (1h 40m vs 4h)',
      'Available capacity (61% utilized vs 92%)',
      'High slot availability in next 2 hours',
      'Acceptable distance (11.4 km from your farm)',
    ],
    contactPhone: '+91 8232-287114',
    operatingHours: '08:30 AM - 05:30 PM',
  },
  {
    id: 'centre-c',
    name: 'Maddur Raitha Seva Kendra',
    code: 'MDR-RSK-02',
    district: 'Mandya',
    address: 'Old BM Road, Maddur Taluk - 571428',
    latitude: 12.5841,
    longitude: 77.0421,
    distanceKm: 15.6,
    capacityQuintalsPerDay: 4000,
    currentCapacityUsedQuintals: 1680,
    capacityUtilizationPercent: 42,
    activeWeighingStations: 3,
    totalWeighingStations: 3,
    queueSize: 14,
    averageWaitMinutes: 55,
    processingRatePerHour: 15,
    status: 'OPTIMAL',
    delayMinutes: 0,
    isRecommended: false,
    recommendationReasons: [
      'Fastest processing rate today',
      'Very low queue (14 farmers ahead)',
    ],
    contactPhone: '+91 8232-233910',
    operatingHours: '09:00 AM - 05:00 PM',
  },
  {
    id: 'centre-d',
    name: 'Srirangapatna Agro Terminal',
    code: 'SRP-AGR-07',
    district: 'Mandya',
    address: 'Near Railway Station, Srirangapatna - 571438',
    latitude: 12.4238,
    longitude: 76.6853,
    distanceKm: 19.8,
    capacityQuintalsPerDay: 3000,
    currentCapacityUsedQuintals: 2550,
    capacityUtilizationPercent: 85,
    activeWeighingStations: 2,
    totalWeighingStations: 3,
    queueSize: 52,
    averageWaitMinutes: 165,
    processingRatePerHour: 11,
    status: 'MODERATE',
    delayMinutes: 20,
    delayReason: 'Weighing bridge calibration routine',
    isRecommended: false,
    contactPhone: '+91 8232-252190',
    operatingHours: '08:00 AM - 06:00 PM',
  },
];

export const generateDynamicSlots = (centreId: string): DynamicSlot[] => {
  return [
    {
      id: `${centreId}-slot-1`,
      centreId,
      date: 'Today',
      arrivalWindowStart: '10:30 AM',
      arrivalWindowEnd: '11:00 AM',
      expectedWaitMinutes: 25,
      confidenceScore: 'HIGH',
      availableCapacityQuintals: 450,
      maxTokens: 20,
      bookedTokens: 14,
      isRecommendedSlot: true,
    },
    {
      id: `${centreId}-slot-2`,
      centreId,
      date: 'Today',
      arrivalWindowStart: '11:30 AM',
      arrivalWindowEnd: '12:00 PM',
      expectedWaitMinutes: 38,
      confidenceScore: 'HIGH',
      availableCapacityQuintals: 300,
      maxTokens: 20,
      bookedTokens: 17,
      isRecommendedSlot: false,
    },
    {
      id: `${centreId}-slot-3`,
      centreId,
      date: 'Today',
      arrivalWindowStart: '02:10 PM',
      arrivalWindowEnd: '02:30 PM',
      expectedWaitMinutes: 45,
      confidenceScore: 'MEDIUM',
      availableCapacityQuintals: 600,
      maxTokens: 25,
      bookedTokens: 11,
      isRecommendedSlot: false,
    },
    {
      id: `${centreId}-slot-4`,
      centreId,
      date: 'Today',
      arrivalWindowStart: '03:45 PM',
      arrivalWindowEnd: '04:15 PM',
      expectedWaitMinutes: 52,
      confidenceScore: 'MEDIUM',
      availableCapacityQuintals: 500,
      maxTokens: 25,
      bookedTokens: 8,
      isRecommendedSlot: false,
    },
  ];
};

export const initialActiveBooking: Booking = {
  id: 'book-8821',
  tokenNumber: 'KFN-2847',
  farmerId: 'farmer-101',
  farmerName: 'Ramesh Patel',
  farmerPhone: '+91 98451 23890',
  centreId: 'centre-b',
  centreName: 'Gejjalagere Farmers Sub-Centre',
  cropType: 'Paddy (Grade A)',
  variety: 'JGL 1798 (BPT-5204)',
  expectedQuantityQuintals: 35,
  bookingDate: 'Today, 27 Aug',
  scheduledArrivalWindow: {
    start: '02:10 PM',
    end: '02:30 PM',
  },
  dynamicArrivalWindow: {
    start: '02:10 PM',
    end: '02:30 PM',
  },
  currentPositionInQueue: 18,
  farmersAhead: 17,
  estimatedWaitMinutes: 138, // 2h 18m
  estimatedProcurementTime: '02:35 PM',
  actionState: 'WAIT_AT_HOME',
  centreDelayMinutes: 0,
  createdAt: '2026-08-27T08:30:00Z',
  updatedAt: '2026-08-27T10:15:00Z',
};

export const initialProcurementRecord: ProcurementRecord = {
  id: 'proc-5501',
  tokenNumber: 'KFN-2847',
  farmerId: 'farmer-101',
  centreId: 'centre-b',
  cropType: 'Paddy (Grade A)',
  weighingStationNumber: 2,
  grossWeightQuintals: 42.5,
  tareWeightQuintals: 7.5,
  netWeightQuintals: 35.0,
  moisturePercent: 12.8,
  foreignMatterPercent: 0.6,
  qualityGrade: 'GRADE_A',
  mspRatePerQuintal: 2183,
  totalProcurementAmount: 76405,
  billNumber: 'BILL-KA-MND-2026-9812',
  billGeneratedAt: '27 Aug 2026, 03:15 PM',
  stageTimestamps: {
    arrivedAt: '02:05 PM',
    weighingStartedAt: '02:22 PM',
    weighingCompletedAt: '02:40 PM',
    qualityAssessedAt: '02:52 PM',
    procurementAcceptedAt: '03:05 PM',
    billGeneratedAt: '03:15 PM',
    paymentInitiatedAt: '03:18 PM',
  },
};

export const initialPaymentRecord: PaymentRecord = {
  id: 'pay-7709',
  tokenNumber: 'KFN-2847',
  farmerId: 'farmer-101',
  farmerName: 'Ramesh Patel',
  amount: 76405,
  status: 'BANK_PROCESSING',
  billNumber: 'BILL-KA-MND-2026-9812',
  transactionRef: 'PFMS20260827981244X',
  beneficiaryName: 'RAMESH PATEL',
  accountNumberMasked: 'XXXX-XXXX-9142',
  bankName: 'State Bank of India',
  ifscCode: 'SBIN0001234',
  pfmsBatchNumber: 'PFMS-KA-MND-BATCH-441',
  paymentInitiatedAt: '27 Aug 2026, 03:18 PM',
};

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    category: 'QUEUE_UPDATE',
    title: 'Queue Moving Normally',
    message: 'Gejjalagere Sub-Centre is operating at 14 farmers/hour. You are 17 farmers away.',
    timestamp: '15 mins ago',
    read: false,
    severity: 'info',
  },
  {
    id: 'notif-2',
    category: 'ETA_UPDATE',
    title: 'Arrival Window Confirmed',
    message: 'Your dynamic arrival window is 2:10 PM – 2:30 PM. Please wait at home.',
    timestamp: '1 hour ago',
    read: true,
    severity: 'success',
  },
];

export const initialAdminAlerts: AdminAlert[] = [
  {
    id: 'alert-1',
    type: 'PREDICTION',
    centreId: 'centre-a',
    centreName: 'Mandya Central APMC Yard',
    title: 'Centre #27 may exceed storage capacity by 2:00 PM',
    description: 'Current inflow is 28% higher than historical Tuesday average. Yard is at 92% capacity.',
    severity: 'high',
    timestamp: '10 mins ago',
    suggestedAction: 'Reroute incoming slots to Gejjalagere Sub-Centre (61% capacity).',
  },
  {
    id: 'alert-2',
    type: 'ALERT',
    centreId: 'centre-d',
    centreName: 'Srirangapatna Agro Terminal',
    title: 'Processing speed is 23% below normal baseline',
    description: 'Station #3 temporary recalibration slowing intake. Current rate: 11 farmers/hr (expected 15).',
    severity: 'medium',
    timestamp: '25 mins ago',
    suggestedAction: 'Authorize mobile calibration unit dispatch.',
  },
  {
    id: 'alert-3',
    type: 'RECOMMENDATION',
    centreId: 'centre-b',
    centreName: 'Gejjalagere Farmers Sub-Centre',
    title: '320 eligible farmers can potentially be redirected',
    description: 'Surplus capacity of 1,365 quintals available with zero wait-time penalty.',
    severity: 'low',
    timestamp: '40 mins ago',
    suggestedAction: 'Send proactive SMS broadcast for early afternoon arrival windows.',
  },
];
